active: Rig
profiles:
- name: Rig
  mount: Mount
  camera: Main Camera
  guide_camera: Guide Camera
  focuser: Focuser
  filter_wheel: Filter Wheel
  optics: null
- name: Simulateurs
  mount: Mount Simulator
  camera: CCD Imager Simulator
  guide_camera: CCD Guider Simulator
  focuser: CCD Imager Simulator (focuser)
  filter_wheel: CCD Imager Simulator (wheel)
  optics: null
