#!/bin/sh
set -e
case "$1" in
  remove|deconfigure)
    if command -v systemctl >/dev/null 2>&1; then
      systemctl stop noctua 2>/dev/null || true
      systemctl disable noctua 2>/dev/null || true
    fi
    ;;
esac
#DEBHELPER#
exit 0
